# -*- coding: utf-8 -*-
"""KPI_Dictionary_Data_Quality_Contract

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UyV8YMOkUeSOEkkoZF2SoOdblAX1rR06
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd

df = pd.read_csv("retail-data-dictionary.csv")

df.head()

print(df.shape)

print(df.columns.tolist())

df.head()

df.info()

print("Dataset Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nFirst 5 Rows:")
display(df.head())

print("\nDataset Information:")
df.info()

from google.colab import files

uploaded = files.upload()

import pandas as pd

df = pd.read_csv("retail-orders-raw.csv")

df.head()

print("Dataset Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nFirst 5 Rows:")
display(df.head())

print("\nDataset Information:")
df.info()

import pandas as pd
import numpy as np
from datetime import datetime

pd.set_option("display.max_columns", None)

df = pd.read_csv("retail-orders-raw.csv")

print("Dataset loaded successfully!")
print("Shape:", df.shape)

display(df.head())

print("Columns:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

print("\nDataset Information:")
df.info()

df.describe(include="all").T

missing_count = df.isnull().sum()

missing_percentage = (
    df.isnull().mean() * 100
).round(2)

completeness_report = pd.DataFrame({
    "Missing_Count": missing_count,
    "Missing_Percentage": missing_percentage
})

completeness_report

duplicate_count = df.duplicated().sum()

print("Duplicate rows:", duplicate_count)

duplicate_percentage = round(
    df.duplicated().mean() * 100, 2
)

print("Duplicate percentage:", duplicate_percentage, "%")

print("Missing order_id:",
      df["order_id"].isnull().sum())

print("Duplicate order_id:",
      df["order_id"].duplicated().sum())

df["order_date"] = pd.to_datetime(
    df["order_date"],
    errors="coerce"
)

print("Invalid dates:",
      df["order_date"].isnull().sum())

print("Minimum order date:",
      df["order_date"].min())

print("Maximum order date:",
      df["order_date"].max())

df["customer_segment"].value_counts(dropna=False)

valid_segments = [
    "Student",
    "Fresher",
    "Professional"
]

invalid_segments = df[
    ~df["customer_segment"].isin(valid_segments)
]

print("Invalid customer segments:",
      len(invalid_segments))

empty_city = (
    df["city"].isnull() |
    (df["city"].astype(str).str.strip() == "")
).sum()

print("Empty city values:", empty_city)

df["category"].value_counts(dropna=False)

valid_categories = [
    "Learning Kit",
    "Course Access",
    "Mentor Session"
]

invalid_categories = df[
    ~df["category"].isin(valid_categories)
]

print("Invalid categories:",
      len(invalid_categories))

df.select_dtypes(include=np.number).columns.tolist()

print(df.columns.tolist())

df["revenue_calculated"] = (
    df["quantity"] * df["unit_price"]
)

df[[
    "quantity",
    "unit_price",
    "revenue_calculated"
]].head()

total_orders = df["order_id"].nunique()

print("Total Orders:", total_orders)

print(df.columns.tolist())

print(df.columns.tolist())

display(df.head(10))

print(df.dtypes)

missing_report = pd.DataFrame({
    "Column": df.columns,
    "Missing_Count": df.isnull().sum().values,
    "Missing_Percentage": (
        df.isnull().mean().values * 100
    ).round(2)
})

missing_report

duplicate_count = df.duplicated().sum()

print("Total duplicate rows:", duplicate_count)
print(
    "Duplicate percentage:",
    round(df.duplicated().mean() * 100, 2),
    "%"
)

print("Missing order_id:",
      df["order_id"].isnull().sum())

print("Duplicate order_id:",
      df["order_id"].duplicated().sum())

df["order_date"] = pd.to_datetime(
    df["order_date"],
    errors="coerce"
)

print("Invalid dates:",
      df["order_date"].isnull().sum())

print("Minimum date:",
      df["order_date"].min())

print("Maximum date:",
      df["order_date"].max())

print(
    df["customer_segment"]
    .value_counts(dropna=False)
)

print(
    df["customer_segment"]
    .value_counts(dropna=False)
)

valid_segments = [
    "Student",
    "Fresher",
    "Professional"
]

invalid_segments = df[
    ~df["customer_segment"].isin(valid_segments)
]

print(
    "Invalid customer segments:",
    len(invalid_segments)
)

empty_city = (
    df["city"].isna() |
    (df["city"].astype(str).str.strip() == "")
).sum()

print("Empty city values:", empty_city)

print(
    df["category"]
    .value_counts(dropna=False)
)

valid_categories = [
    "Learning Kit",
    "Course Access",
    "Mentor Session"
]

invalid_categories = df[
    ~df["category"].isin(valid_categories)
]

print(
    "Invalid categories:",
    len(invalid_categories)
)

quality_report = pd.DataFrame({
    "Dimension": [
        "Completeness",
        "Uniqueness",
        "Date Validity",
        "Customer Segment Validity",
        "City Completeness",
        "Category Validity"
    ],

    "Result": [
        round(df.notnull().mean().mean() * 100, 2),
        round((1 - df.duplicated().mean()) * 100, 2),
        round(
            df["order_date"].notnull().mean() * 100,
            2
        ),
        round(
            df["customer_segment"]
            .isin(valid_segments)
            .mean() * 100,
            2
        ),
        round(
            (
                df["city"].notna() &
                (df["city"].astype(str).str.strip() != "")
            ).mean() * 100,
            2
        ),
        round(
            df["category"]
            .isin(valid_categories)
            .mean() * 100,
            2
        )
    ]
})

quality_report

quality_report["Status"] = np.where(
    quality_report["Result"] >= 99,
    "PASS",
    "FAIL"
)

quality_report

kpi_dictionary = pd.DataFrame({
    "KPI_Name": [
        "Total Orders",
        "Unique Customer Segments",
        "Orders per City",
        "Orders per Category",
        "Student Order Rate",
        "Fresher Order Rate",
        "Professional Order Rate",
        "Average Orders per City"
    ],

    "Business_Definition": [
        "Total number of unique orders",
        "Number of different customer segments",
        "Number of orders received from each city",
        "Number of orders for each product category",
        "Percentage of orders from Students",
        "Percentage of orders from Freshers",
        "Percentage of orders from Professionals",
        "Average number of orders received per city"
    ],

    "Formula": [
        "COUNT(DISTINCT order_id)",
        "COUNT(DISTINCT customer_segment)",
        "COUNT(order_id) GROUP BY city",
        "COUNT(order_id) GROUP BY category",
        "Student Orders / Total Orders × 100",
        "Fresher Orders / Total Orders × 100",
        "Professional Orders / Total Orders × 100",
        "Total Orders / Number of Cities"
    ],

    "Grain": [
        "Order",
        "Customer Segment",
        "City",
        "Category",
        "Order",
        "Order",
        "Order",
        "City"
    ],

    "Filter": [
        "Valid order_id",
        "Valid customer_segment",
        "Valid order_id",
        "Valid category",
        "customer_segment = Student",
        "customer_segment = Fresher",
        "customer_segment = Professional",
        "Valid city"
    ],

    "Owner": [
        "Sales Manager",
        "Marketing Manager",
        "Operations Manager",
        "Product Manager",
        "Marketing Manager",
        "Marketing Manager",
        "Marketing Manager",
        "Operations Manager"
    ],

    "Refresh_Cadence": [
        "Daily",
        "Weekly",
        "Daily",
        "Daily",
        "Weekly",
        "Weekly",
        "Weekly",
        "Daily"
    ]
})

display(kpi_dictionary)

total_orders = df["order_id"].nunique()

segment_counts = df["customer_segment"].value_counts()

city_counts = df["city"].value_counts()

category_counts = df["category"].value_counts()

student_rate = (
    (df["customer_segment"] == "Student").sum()
    / len(df) * 100
)

fresher_rate = (
    (df["customer_segment"] == "Fresher").sum()
    / len(df) * 100
)

professional_rate = (
    (df["customer_segment"] == "Professional").sum()
    / len(df) * 100
)

average_orders_per_city = (
    total_orders / df["city"].nunique()
)

print("Total Orders:", total_orders)
print("Student Order Rate:", round(student_rate, 2), "%")
print("Fresher Order Rate:", round(fresher_rate, 2), "%")
print("Professional Order Rate:", round(professional_rate, 2), "%")
print("Average Orders per City:", round(average_orders_per_city, 2))

kpi_results = pd.DataFrame({
    "KPI": [
        "Total Orders",
        "Student Order Rate",
        "Fresher Order Rate",
        "Professional Order Rate",
        "Average Orders per City"
    ],

    "Value": [
        total_orders,
        round(student_rate, 2),
        round(fresher_rate, 2),
        round(professional_rate, 2),
        round(average_orders_per_city, 2)
    ]
})

display(kpi_results)

kpi_dictionary.to_excel(
    "KPI_Dictionary.xlsx",
    index=False
)

print("KPI Dictionary created successfully!")

from google.colab import files

files.download("KPI_Dictionary.xlsx")

quality_contract = pd.DataFrame({
    "Dimension": [
        "Completeness",
        "Uniqueness",
        "Validity - Order Date",
        "Validity - Customer Segment",
        "Validity - Category",
        "Consistency",
        "Freshness"
    ],

    "Quality_Rule": [
        "Required fields must not be empty",
        "order_id should be unique",
        "order_date must be a valid date",
        "Only Student, Fresher, Professional allowed",
        "Only Learning Kit, Course Access, Mentor Session allowed",
        "Related fields must follow defined business rules",
        "Data should be refreshed within the agreed period"
    ],

    "Threshold": [
        ">= 99%",
        ">= 99%",
        "100%",
        "100%",
        "100%",
        "100%",
        "<= 24 hours"
    ],

    "Failure_Action": [
        "Investigate missing records",
        "Investigate duplicate orders",
        "Reject invalid dates",
        "Correct invalid segment",
        "Correct invalid category",
        "Investigate inconsistent records",
        "Notify data owner"
    ],

    "Escalation_Owner": [
        "Data Owner",
        "Data Owner",
        "Data Owner",
        "Marketing Manager",
        "Product Manager",
        "Data Owner",
        "Operations Manager"
    ]
})

display(quality_contract)

quality_contract.to_excel(
    "Data_Quality_Contract.xlsx",
    index=False
)

print("Data Quality Contract created successfully!")

from google.colab import files

files.download("Data_Quality_Contract.xlsx")

final_quality = quality_report.copy()

final_quality["Threshold"] = [
    99,
    99,
    100,
    100,
    100,
    99
]

final_quality["Status"] = np.where(
    final_quality["Result"] >= final_quality["Threshold"],
    "PASS",
    "FAIL"
)

display(final_quality)

final_quality.to_excel(
    "Data_Quality_Results.xlsx",
    index=False
)

print("Quality results saved successfully!")

final_quality.to_excel(
    "Data_Quality_Results.xlsx",
    index=False
)

print("Quality results saved successfully!")